package com.india.railway.dto;

import com.india.railway.service.mysql.AutoGeneratedValue;

public class TrainDTO {

    private String id;
    private String train_name;

    public String getTrain_number() {
        return train_number;
    }

    public void setTrain_number(String train_number) {
        this.train_number = train_number;
    }

    public String getTrain_name() {
        return train_name;
    }

    public void setTrain_name(String train_name) {
        this.train_name = train_name;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    private String train_number;

}
