package com.india.railway.dto;

import com.india.railway.service.mysql.AutoGeneratedValue;
import jakarta.persistence.Column;

public class UserDTO {


    private String id;
    private String userNumber;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserNumber() {
        return userNumber;
    }

    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    private String username;
}
