package com.india.railway.model.mysql;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.springframework.format.annotation.DateTimeFormat;

import com.india.railway.service.mysql.AutoGeneratedValue;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data // getter and setter and tostring
@AllArgsConstructor
@NoArgsConstructor
// @EntityListeners(CustomIdGenerationListener.class)
@Table(name = "passenger")
public class Passenger extends Auditable {

        @Id
        // @GeneratedValue(strategy = GenerationType.IDENTITY)
        @AutoGeneratedValue(entityName = "passenger_entity")
        private Long id;

        @Size(min = 5, max = 15, message = "Name should be atlease 5 characters and not more than 15 characters")
        private String name;

        @Min(value = 18, message = "Age must be greater than or equal to 18")
        private int age;

        @NotNull(message = "Aadhar number cannot be null")
        @Pattern(regexp = "\\d{12}", message = "Aadhar number must be exactly 12 digits")
        private String aadhar_no;

        @Email(message = "Email should be valid")
        @NotBlank(message = "Email is mandatory")
        private String email;

        @NotNull(message = "cell no number cannot be null")
        @Pattern(regexp = "\\+91[0-9]{10}", message = "Phone number must start with +91 and be followed by 10 digits")
        private String cellno;

        @NotNull(message = "Date of birth cannot be null")
        @Past(message = "Date of birth must be a past date")
        @DateTimeFormat(pattern = "yyyy-MM-dd") // Ensures proper date formatting
        private LocalDate dob;

        @NotNull(message = "Pincode number cannot be null")
        @Pattern(regexp = "\\d{6}", message = "Pincode number must be exactly 6 digits")
        private String pincode;

        @DecimalMin(value = "100.00", message = "Salary must be at least 100.00")
        @DecimalMax(value = "100000.00", message = "Salary cannot exceed 10000.00")
        private Long salary;

        // extra fileds for verification
        private String pnumber;
        private String gender;
        // private String dob;

        @Valid // Ensure this is present to validate related entities (user)
               // @Size(min = 1, message = "Passenger must be mapped to user.")
        @OneToOne(cascade = CascadeType.ALL, optional = false)
        @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false) // Foreign key in User table
        @NotNull(message = "user must not be null")
        private User user;

        // ------------------------------------------------------------------

        @OneToMany(cascade = CascadeType.ALL)
        @JoinTable(name = "passenger_address", // Name of the join table
                        joinColumns = @JoinColumn(name = "passenger_id", referencedColumnName = "id"), // Foreign key in
                                                                                                       // join table
                                                                                                       // pointing to
                                                                                                       // Passenger
                        inverseJoinColumns = @JoinColumn(name = "address_id", referencedColumnName = "id") // Foreign
                                                                                                           // key in
                                                                                                           // join
        )
        // @NotEmpty(message = "Passenger must have at least one address.")
        @Valid // Ensure this is present to validate related entities (address)
        @Size(min = 1, message = "Passenger must have at least one address.") // Ensure at least one post
        private List<Address> address;

        // --------------------------------------------------------------------------

        // @ManyToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch =
        // FetchType.LAZY)
        @ManyToMany(fetch = FetchType.LAZY)
        @JoinTable(name = "passenger_train", // Name of the join table
                        joinColumns = @JoinColumn(name = "passenger_id"), // Column in the join table for Student
                        inverseJoinColumns = @JoinColumn(name = "train_id") // Column in the join table for Course
        )
        @Valid
        // @NotEmpty(message = "A passenger must be book ticket in at least one train.")
        private Set<Train> trains = new HashSet<>();
        // private Set<Department> departments = new HashSet<>();

        // @NotNull(message = "train must not be null")
        // @Size(min = 1, message = "Passenger must have at least one address.")
        // private Set<Train> trains = new HashSet<>();

        // @NotNull(message = "train must not be null")
        // @Size(min = 1, message = "Passenger must have at least one address.")

        // --------------------------------------------------------------------------------

}
