package com.india.railway.model.mysql;

import java.time.LocalDate;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

import com.india.railway.service.mysql.AutoGeneratedValue;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import jakarta.validation.Valid;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Past;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@EqualsAndHashCode(callSuper = true)
@Entity
@Data // getter and setter and tostring
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "passenger")
public class Passenger extends Auditable {

        @Id
        @AutoGeneratedValue(entityName = "passenger_entity")
        private String id;

        @NotNull(message = "name must not be null")
        @Size(min = 5, max = 15, message = "Name should be atlease 5 characters and not more than 15 characters")
        private String name;

        @NotNull
        @Min(value = 18, message = "Age must be greater than or equal to 18")
        private int age;

        @NotNull(message = "Aadhar number cannot be null")
        @Pattern(regexp = "\\d{12}", message = "Aadhar number must be exactly 12 digits")
        private String aadhar_no;

        @Email(message = "Email should be valid")
        @NotBlank(message = "Email is mandatory")
        private String email;

        @NotNull(message = "cell no number cannot be null")
        @Pattern(regexp = "\\+91[0-9]{10}", message = "Phone number must start with +91 and be followed by 10 digits")
        private String cellno;

        @NotNull(message = "Date of birth cannot be null")
        @Past(message = "Date of birth must be a past date")
        @DateTimeFormat(pattern = "yyyy-MM-dd")
        private LocalDate dob;

        @NotNull(message = "Pincode number cannot be null")
        @Pattern(regexp = "\\d{6}", message = "Pincode number must be exactly 6 digits")
        private String pincode;

        @NotNull
        @DecimalMin(value = "100.00", message = "Salary must be at least 100.00")
        @DecimalMax(value = "100000.00", message = "Salary cannot exceed 10000.00")
        private Long salary;

        @AutoGeneratedValue(entityName = "passenger_pnr_number")
        private String pnumber;
        private String gender;


        @OneToOne(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
        @JoinColumn(name = "user_id", referencedColumnName = "id", nullable = false)
        @NotNull(message = "user must not be null")
        @Valid
        private User user;

        @OneToMany(cascade = CascadeType.ALL,fetch = FetchType.LAZY)
        @JoinTable(name = "passenger_address", // Name of the join table
                        joinColumns = @JoinColumn(name = "passenger_id", referencedColumnName = "id"),
                        inverseJoinColumns = @JoinColumn(name = "address_id", referencedColumnName = "id") )

        @Size(min = 1, message = "Passenger must have at least one address.")
        private List<Address> address;



        @ManyToMany(cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
        @JoinTable(name = "passenger_train", // Name of the join table
                joinColumns = @JoinColumn(name = "passenger_id", referencedColumnName = "id"),

                inverseJoinColumns = @JoinColumn(name = "train_id", referencedColumnName = "id")

        )
        private Set<Train> trains = new HashSet<>();


}
