package com.india.railway.model.mysql;

import com.india.railway.service.mysql.AutoGeneratedValue;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;
import lombok.*;

import java.util.*;

@Entity
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "train")
@Getter
@Setter
@ToString(exclude = "passengers")
public class Train {

    @Id
   // @GeneratedValue(strategy = GenerationType.IDENTITY)
    @AutoGeneratedValue(entityName = "train_entity")
    private String id;
    private String train_name;

    @AutoGeneratedValue(entityName = "train_number")
    private String train_number;

    private String start_date;
    private String end_date;
    private String noofcoaches;
    private String status; // if cancel or ontime
    private String start_station;
    private String end_station;

    // @ManyToMany(mappedBy = "trains")
    // @NotEmpty(message = "A train must have at least one passenger.")
    @ManyToMany(mappedBy = "trains", fetch = FetchType.LAZY)
    private Set<Passenger> passengers = new HashSet<>();

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Train)) return false;
        Train other = (Train) o;
        return id != null && id.equals(other.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}