package com.india.railway.service.mysql;

import java.lang.reflect.Field;
import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.ManyToOne;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.OneToMany;
import jakarta.persistence.OneToOne;
@Slf4j
@Service
public class AutoCodeGeneratorService {

    @Autowired
    private TransactionIdGeneratorService transactionIdGeneratorService;

    public void generateId(Object entity) throws IllegalAccessException {
        Set<Object> visited = new HashSet<>();
        generateIdRecursive(entity, visited);
    }


    private void generateIdRecursive(Object entity, Set<Object> visited)
            throws IllegalAccessException {

        if (entity == null || visited.contains(entity)) {
            return;
        }

        // 🚨 CRITICAL FIX: process ONLY JPA entities
        if (!isJpaEntity(entity.getClass())) {
            return;
        }

        visited.add(entity);

        log.info("processing entity: {}",
                entity.getClass().getSimpleName());

        for (Field field : entity.getClass().getDeclaredFields()) {


            log.info("processing attribute: {}",field.getName());


            // -------- 1️⃣ ID generation ----------
            if (field.isAnnotationPresent(AutoGeneratedValue.class)) {
                field.setAccessible(true);

                if (field.get(entity) == null) {
                    log.info("generating auto generation value value for the entity field: {}.{}",entity.getClass().getSimpleName(),field.getName());
                    AutoGeneratedValue ann = field.getAnnotation(AutoGeneratedValue.class);
                    String fieldName = field.getName();

                    String nextId = transactionIdGeneratorService
                            .generateNextId(ann.entityName(), ann.incrementSize(),fieldName);

                    log.info("{} is generated  entity field: {}.{}",nextId,entity.getClass().getSimpleName(),field.getName());

                    field.set(entity, nextId);
                }
                continue;
            }

            // -------- 2️⃣ Relations only ----------
            if (!isRelationField(field)) {
                continue;
            }

            field.setAccessible(true);
            Object value = field.get(entity);

            if (value == null) continue;

            // -------- 3️⃣ Collection of entities ----------
            if (value instanceof Iterable<?>) {
                for (Object child : (Iterable<?>) value) {
                    generateIdRecursive(child, visited);
                }
            }
            // -------- 4️⃣ Single entity ----------
            else {
                generateIdRecursive(value, visited);
            }
        }
    }

    private boolean isJpaEntity(Class<?> clazz) {
        return clazz.isAnnotationPresent(jakarta.persistence.Entity.class);
    }

    // for one to one and many to many will be added later those are lov
    // so not needed to generate auto fields for those entity fields
    private boolean isRelationField(Field field) {
        return field.isAnnotationPresent(OneToMany.class)
                || field.isAnnotationPresent(OneToOne.class)
                || field.isAnnotationPresent(ManyToOne.class)
                || field.isAnnotationPresent(ManyToMany.class);


    }


   /* public void generateId(Object entity) throws IllegalAccessException {
        Field[] fields = entity.getClass().getDeclaredFields();

        for (Field field : fields) {
            if (field.isAnnotationPresent(AutoGeneratedValue.class)) {
                AutoGeneratedValue customGeneratedValue = field.getAnnotation(AutoGeneratedValue.class);

                String entityName = customGeneratedValue.entityName();
                int idvalue = customGeneratedValue.incrementSize();
                // Generate the next ID using the TableBasedIdGeneratorService
                String nextId = transactionIdGeneratorService.generateNextId(entityName,
                        idvalue);

                // Set the generated ID to the field
                field.setAccessible(true);
                field.set(entity, nextId);
            }
        }*/
    }


