
package com.india.railway.service.mysql;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGeneratedValue {
    String entityName(); // Name of the sequence

    int incrementSize() default 1; // Increment size (optional)
}