package com.india.railway.service.mysql;

import java.lang.reflect.Field;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class AutoCodeGeneratorService {

    @Autowired
    private TransactionIdGeneratorService transactionIdGeneratorService;

    public void generateId(Object entity) throws IllegalAccessException {
        Field[] fields = entity.getClass().getDeclaredFields();

        for (Field field : fields) {
            if (field.isAnnotationPresent(AutoGeneratedValue.class)) {
                AutoGeneratedValue customGeneratedValue = field.getAnnotation(AutoGeneratedValue.class);

                String entityName = customGeneratedValue.entityName();
                int idvalue = customGeneratedValue.incrementSize();
                // Generate the next ID using the TableBasedIdGeneratorService
                Long nextId = transactionIdGeneratorService.generateNextId(entityName,
                        idvalue);

                // Set the generated ID to the field
                field.setAccessible(true);
                field.set(entity, nextId);
            }
        }
    }

}
